import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GitHub Roaster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-teal-600 p-4">
          <div className="container mx-auto">
            <Link href="/" className="text-white font-bold text-lg">
              Home
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
